---

- name: Create database
  postgresql_db:
    name: "{{ item.value.name }}"
    encoding: UTF-8
    owner: "{{ item.value.owner }}"
  become: true
  become_user: postgres
  with_dict: "{{ postgresql.databases }}"
