---

- import_tasks: install.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - postgresql

- import_tasks: users.yml
  when: postgresql.users is defined
  tags:
    - postgresql

- import_tasks: databases.yml
  when: postgresql.databases is defined
  tags:
    - postgresql

- import_tasks: exporter.yml
  when: postgresql_exporter is defined
  tags:
    - postgresql
