---

- name: Prepare folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ wallet.service_dir }}"
    - "{{ wallet.conf_dir }}"

- name: Assemble config files
  template: src={{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - src: docker-compose.yml
      dest: "{{ wallet.service_dir }}/docker-compose.yml"
    - src: .env
      dest: "{{ wallet.service_dir }}/.env"

- name: Generate RSA keypair for tokens
  openssh_keypair:
    path: "{{ wallet.conf_dir }}/wallet.key"
