---

- name: Set facts
  set_fact:
    wallet_dir: "{{ playbook_dir }}/../wallet"

- name: Checkout repo
  git:
    repo: "{{ wallet.repo }}"
    dest: "{{ wallet_dir }}"
    version: develop
    update: no

- name: Create virtual environment
  shell: $(brew --cellar python)/3.7.0/bin/python3 -m venv venv
  args:
    chdir: "{{ wallet_dir }}"
    creates: "{{ wallet_dir }}/venv"

- name: Assemble local env
  template: src=".env.local.j2" dest="{{ wallet_dir }}/.env"
