---

- name: Prepare folders
  file: path="{{ item }}" state=directory
  with_items:
    - /etc/nginx/conf.d
    - /opt/services/registry
    - /var/containers/registry

- name: Assemble config
  template: src="{{ item['src'] }}" dest="{{ item['dest']}}"
  with_items:
    - src: nginx.conf.j2
      dest: /etc/nginx/conf.d/registry.conf
    - src: config.yml.j2
      dest: /opt/services/registry/config.yml
    - src: docker-compose.yml.j2
      dest: /opt/services/registry/docker-compose.yml

- name: Install packages
  apt: name="{{ item }}"
  with_items:
    - python-passlib

- name: Assemble basic auth htpasswd
  htpasswd:
    path: /etc/nginx/conf.d/registry.htpasswd
    name: "{{ registry.user }}"
    password: "{{ registry.password }}"

- name: Configure garbage collection
  cron:
    name: "registry garbage collect"
    job: "docker exec {{ registry.container }} registry garbage-collect /etc/docker/registry/config.yml"
    minute: 0
    hour: 2
    weekday: 1
