---

- name: Prepare folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ services_dir }}/consul"
    - "{{ consul.conf_dir }}"

- name: Assemble config files
  template: src={{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - src: config.json
      dest: "{{ services_dir }}/consul/config.json"
    - src: docker-compose.yml
      dest: "{{ services_dir }}/consul/docker-compose.yml"
  notify: restart consul

- name: Assemble consul service config
  template: src={{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - src: consul.json
      dest: "{{ consul.conf_dir }}/consul.json"
  notify: reload consul

- name: Run service
  shell: docker-compose up -d chdir={{ services_dir }}/consul
