---

- name: Install packages
  apt: name="{{ item }}"
  when: env != 'local'
  with_items:
    - python-passlib

- name: Assemble basic auth htpasswd
  htpasswd:
    path: /etc/nginx/conf.d/consul.htpasswd
    name: "{{ consul.web.user }}"
    password: "{{ consul.web.password }}"
  when: env != 'local'

- name: Assemble nginx config
  template: src=nginx.conf.j2 dest={{ services_dir }}/loadbalancer/conf.d/consul.conf
