---

- name: Prepare folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ loadbalancer.service_dir }}/consul"

- name: Install packages
  apt:
    name:
      - python-passlib
  when: env != 'develop'

- name: Assemble basic auth htpasswd
  htpasswd:
    path: "{{ loadbalancer.conf_dir }}/consul.htpasswd"
    name: "{{ loadbalancer.consul.auth.user }}"
    password: "{{ loadbalancer.consul.auth.password }}"
  when: env != 'develop'

- name: Assemble nginx config
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
    - src: consul-template.conf.j2
      dest: "{{ loadbalancer.templates_dir }}/consul.conf"

- name: Assemble consul-template service config
  template:
    src: consul-template.service.j2
    dest: "{{ loadbalancer.service_dir }}/consul/run"
    mode: 'u+x'
