---

- hosts: localhost
  vars_files:
    - 'environments/digitalocean/credentials.yml'
  roles:
    - role: digitalocean
      tags:
        - postgresql
        - loadbalancer
        - passport
        - wallet


- hosts: droplets
  vars_files:
    - 'environments/digitalocean/credentials.yml'

  roles:
    - role: postgresql
    - role: loadbalancer
    - role: passport
      when: passport is defined
    - role: wallet
      when: wallet is defined

  tasks:
    - include_role:
        name: consul
        tasks_from: loadbalancer
      when: consul is defined
      tags:
        - loadbalancer

