---

collections:
  - name: clayman083.cluster
    version: 1.1.1
    source: https://galaxy.ansible.com

roles:
  - src: https://github.com/clayman083/ansible-certificates
    version: v1.0.0
    name: certificates

  - src: https://github.com/clayman083/ansible-docker
    version: 1.3.0
    name: docker

  - src: https://github.com/clayman083/ansible-vault
    version: v0.2.0
    name: vault

  - src: https://github.com/clayman083/ansible-postgresql
    version: v0.2.1
    name: postgresql
