---

groups:
  - name: nodes
    rules:
      - alert: high_cpu_load
        expr: node_load1 > 1.5
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "High request latency"
          description: "Docker host is under high load, the avg load 1m is at {{ $value }}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

      - alert: high_memory_load
        expr: (node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100 > 80
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Server memory is almost full"
          description: "Docker host memory usage is {{ humanize $value }}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."
      
      - alert: high_storage_load
        expr: (node_filesystem_size_bytes{mountpoint="/rootfs"} - node_filesystem_free_bytes{mountpoint="/rootfs"}) / node_filesystem_size_bytes{mountpoint="/rootfs"} * 100 > 80
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Node storage is almost full"
          description: "Docker host storage usage is {{ humanize $value }}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."