---

# Common settings
env: develop

credentials_path: "{{ inventory_dir }}/.credentials/"

services_dir: /opt/services

# Users settings
users:
  - name: clayman
    group: clayman
    sudoer: true
  - name: backups
    group: backups
  - name: travis
    group: travis
