---

# Common settings
env: develop

credentials_path: "{{ inventory_dir }}/.credentials"

services_dir: /opt/services

projects_dir: /home/{{ ansible_user }}/Developer

domain: dev.clayman.pro

timezone: 'Asia/Yekaterinburg'


# Users settings
users:
  - name: clayman
    group: clayman
    sudoer: true
  - name: backups
    group: backups
  - name: travis
    group: travis


# Certificates settings
certificates:
  dir: "{{ inventory_dir }}/.certificates"

  authority:
    common_name: Development CA
    days: 3650

  certificates:
    - name: consul
      path: domains/consul
      days: 365
      domains:
        - "{{ domain }}"
        - "consul.{{ domain }}"

    - name: vault
      path: domains/vault
      days: 365
      domains:
        - "{{ domain }}"
        - "vault.{{ domain }}"

    - name: prometheus
      path: domains/prometheus
      days: 365
      domains:
        - "{{ domain }}"
        - "prometheus.{{ domain }}"

    - name: grafana
      path: domains/grafana
      days: 365
      domains:
        - "{{ domain }}"
        - "grafana.{{ domain }}"

    - name: apollo
      path: domains/apollo
      days: 365
      domains:
        - "{{ domain }}"
        - "apollo.{{ domain }}"

    - name: passport
      path: domains/passport
      days: 365
      domains:
        - "{{ domain }}"
        - "passport.{{ domain }}"

    - name: wallet
      path: domains/wallet
      days: 365
      domains:
        - "{{ domain }}"
        - "wallet.{{ domain }}"
