---

private_network: "{{ ansible_eth1['ipv4'] }}"
public_network: "{{ ansible_eth1['ipv4'] }}"
docker_network: "{{ ansible_docker0['ipv4'] }}"


consul:
    host: "{{ private_network.address }}"
    port: 8500
