---

- name: Prepare folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ services_dir }}/loadbalancer"
    - "{{ services_dir }}/loadbalancer/conf.d"
    - "{{ services_dir }}/loadbalancer/consul-templates"
    - "{{ services_dir }}/loadbalancer/service/nginx"
    # - "/etc/consul-templates"
    # - "/etc/letsencrypt"
    # - "/etc/nginx/conf.d"
    # - "/etc/service/nginx"
    # - "/opt/services/loadbalancer"
    # - "/var/www"
  tags:
    - loadbalancer

- name: Upload service file
  copy:
    src: nginx.service
    dest: "{{ services_dir }}/loadbalancer/service/nginx/run"
    mode: "a+x"
  tags:
    - loadbalancer

- name: Upload docker compose file
  copy:
    src: "{{ item }}"
    dest: "{{ services_dir }}/loadbalancer/{{ item }}"
  with_items:
    - Dockerfile
    - nginx.conf
  tags:
    - loadbalancer

- name: Assemble docker-compose file
  template: src=docker-compose.yml.j2 dest={{ services_dir }}/loadbalancer/docker-compose.yml
  tags:
    - loadbalancer