---

- hosts: localhost

  tasks:
    - name: Prepare folders
      file: path="{{ item }}" state=directory
      with_items:
        - "{{ credentials_path }}/services/consul"
      tags:
        - consul

    - name: Generate consul encrypt
      shell: openssl rand -base64 32 > consul.encrypt
      args:
        chdir: "{{ credentials_path }}/services/consul"
        creates: consul.encrypt
      tags:
        - consul


- hosts: servers
  become: true

  roles:
    - role: dnsmasq
    - role: consul
    # - role: loki
    # - role: prometheus

  tasks:
    - name: Add exporter to Consul Catalog
      import_role:
        name: consul
        tasks_from: services
      when: services|default(False)
      tags:
        - consul


- hosts: loadbalancers
  become: true

  roles:
    - role: traefik

  tasks:
    - name: Generate htpasswd for traefik
      htpasswd:
        path: "{{ traefik.conf_dir }}/consul.htpasswd"
        name: consul
        password: consul
      tags:
        - traefik


- hosts: databases
  become: true

  roles:
    - role: postgresql


- hosts: monitoring
  become: true

  roles:
    - role: grafana


- hosts: secrets
  become: true

  roles:
    - role: vault
