---

- hosts: localhost

  roles:
    - role: credentials


- hosts: servers
  become: true

  collections:
    - clayman083.cluster

  roles:
    # Service discovery
    - role: dnsmasq
    - role: consul

    - role: minio
      when: minio_enabled|default(False)

    #  Monitoring
    - role: prometheus
    - role: loki
    - role: grafana
      when: grafana_enabled|default(False)

  tasks:
    - name: Add services to Consul Catalog
      import_role:
        name: consul
        tasks_from: services
      tags:
        - consul


- hosts: lb
  become: true

  collections:
    - clayman083.cluster

  roles:
    - role: traefik
      when: traefik_enabled|default(False)

  tasks:
    - name: Add services to Consul Catalog
      import_role:
        name: consul
        tasks_from: services
      vars:
        services:
          - name: traefik
            entries:
              - "{{ traefik_exporter_service }}"
      tags:
        - consul


- hosts: databases
  become: true

  roles:
    - role: postgresql


- hosts: secrets
  become: true

  roles:
    - role: vault

