---

- hosts: secrets
  become: true

  roles:
    - role: vault

  tasks:
    - name: Add service to Consul Catalog
      include_role:
        name: consul
        tasks_from: services
      vars:
        services: "{{ consul_services|default([]) }}"


- hosts: loadbalancers
  become: true

  tasks:
    - name: Add service config to Nginx
      include_role:
        name: nginx
        tasks_from: domains
      tags:
        - nginx
