---

- hosts: localhost

  tasks:
    - name: Prepare folders
      file: path="{{ item }}" state=directory
      with_items:
        - "{{ credentials_path }}/services/consul"
      tags:
        - consul

    - name: Generate consul encrypt
      shell: openssl rand -base64 32 > consul.encrypt
      args:
        chdir: "{{ credentials_path }}/services/consul"
        creates: consul.encrypt
      tags:
        - consul


- hosts: servers
  become: true

  roles:
    - role: dnsmasq
    - role: consul

  tasks:
    - name: Add exporter to Consul Catalog
      include_role:
        name: consul
        tasks_from: services
      vars:
        services: "{{ consul_services|default([]) }}"
      tags:
        - consul


- hosts: loadbalancers
  become: true

  roles:
    - role: nginx

  tasks:
    - name: Add service config to Nginx
      include_role:
        name: nginx
        tasks_from: domains
      tags:
        - nginx


