---

- hosts: swarm
  become: true

  vars:
    swarm_tokens_path: "{{ credentials_path }}/services/swarm"

  tasks:
    - name: Create swarm
      import_role:
        name: docker
        tasks_from: swarm
      tags:
        - swarm

