---

swarm_node_labels:
  tier: production

swarm_networks:
  - name: backend
    attachable: true
    driver: overlay
    ipam_config:
      - subnet: 10.8.0.0/24


consul:
  agent:
    server: true

  exporter:
    enabled: true


services:
  - name: consul
    entries:
      - name: consul-web
        host: "{{ consul.host }}"
        port: "{{ consul.port }}"
        tags:
          - "{{ env }}"
          - "traefik.enable=true"
          - "traefik.http.routers.consul-web.rule=Host(`consul.dev.clayman.pro`)"
          - "traefik.http.routers.consul-web.entrypoints=web"
          - "traefik.http.routers.consul-web.service=consul-web"
          - "traefik.http.routers.consul-web.middlewares=consul-web-redirect@consulcatalog"
          - "traefik.http.routers.consul-web-secure.rule=Host(`consul.dev.clayman.pro`)"
          - "traefik.http.routers.consul-web-secure.entrypoints=websecure"
          - "traefik.http.routers.consul-web-secure.service=consul-web"
          - "traefik.http.routers.consul-web-secure.middlewares=consul-web-auth@consulcatalog"
          - "traefik.http.routers.consul-web-secure.tls=true"
          - "traefik.http.middlewares.consul-web-auth.basicauth.usersfile=/etc/traefik/conf.d/consul.htpasswd"
          - "traefik.http.middlewares.consul-web-redirect.redirectscheme.scheme=https"
          - "traefik.http.middlewares.consul-web-redirect.redirectscheme.permanent=true"
        meta:
          hostname: "{{ ansible_hostname }}"
          tier: "{{ env }}"
      - name: consul-exporter
        host: "{{ consul.exporter.host }}"
        port: "{{ consul.exporter.port }}"
        tags:
          - "{{ env }}"
        meta:
          hostname: "{{ ansible_hostname }}"
          tier: "{{ env }}"
        checks:
          - id: "consul_exporter_check"
            name: "Prometheus exporter for Consul"
            http: "http://{{ consul.exporter.host }}:{{ consul.exporter.port }}"
            interval: "20s"

  - name: prometheus
    entries:
      - name: node-exporter
        host: "{{ prometheus.node_exporter.host }}"
        port: "{{ prometheus.node_exporter.port }}"
        tags:
          - "{{ env }}"
        meta:
          hostname: "{{ ansible_hostname }}"
          tier: "{{ env }}"
        checks:
          - id: "node_exporter_check"
            name: "Prometheus exporter for Node metrics"
            http: "http://{{ prometheus.node_exporter.host }}:{{ prometheus.node_exporter.port }}"
            interval: "20s"
      - name: cadvisor-exporter
        host: "{{ prometheus.cadvisor_exporter.host }}"
        port: "{{ prometheus.cadvisor_exporter.port }}"
        tags:
          - "{{ env }}"
        meta:
          hostname: "{{ ansible_hostname }}"
          tier: "{{ env }}"
        checks:
          - id: "cadvisor_exporter_check"
            name: "Prometheus exporter for Cadvisor metrics"
            http: "http://{{ prometheus.cadvisor_exporter.host }}:{{ prometheus.cadvisor_exporter.port }}"
            interval: "20s"
      - name: docker-exporter
        host: "{{ prometheus.docker_exporter.host }}"
        port: "{{ prometheus.docker_exporter.port }}"
        tags:
          - "{{ env }}"
        meta:
          hostname: "{{ ansible_hostname }}"
          tier: "{{ env }}"
        checks:
          - id: "docker_exporter_check"
            name: "Prometheus exporter for Docker engine metrics"
            http: "http://{{ prometheus.docker_exporter.host }}:{{ prometheus.docker_exporter.port }}/metrics"
            interval: "20s"


  - name: traefik
    entries:
      # - name: traefik
      #   host: "{{ traefik.host }}"
      #   port: "{{ traefik.port }}"
      #   tags:
      #     - "{{ env }}"
      #   meta:
      #     hostname: "{{ ansible_hostname }}"
      #     tier: "{{ env }}"
      - name: traefik-exporter
        host: "{{ traefik.exporter.host }}"
        port: "{{ traefik.exporter.port }}"
        tags:
          - "{{ env }}"
        meta:
          hostname: "{{ ansible_hostname }}"
          tier: "{{ env }}"


traefik:
  service: traefik.service.consul

  service_dir: "{{ services_dir }}/traefik"
  certs_dir: "{{ services_dir }}/traefik/certs"
  conf_dir: "{{ services_dir }}/traefik/conf.d"

  entrypoints:
    insecure:
      host: "{{ public_network.address }}"
      port: 80
    secure:
      host: "{{ public_network.address }}"
      port: 443
    traefik:

  api:
    host: "{{ private_network.address }}"
    port: 8081

  consul:
    enabled: true
    host: "{{ consul.host }}"
    port: "{{ consul.port }}"

  container:
    image: traefik:v2.1.3
    name: traefik
    restart: always
    network: ''
    dns: "{{ private_network.address }}"

    syslog:
      enabled: false
      host: unixgram:///dev/log
      tag: traefik

  exporter:
    enabled: true

    host: "{{ private_network.address }}"
    port: 8080

  certificates:
    - cert: "{{ services_dir }}/traefik/certs/consul.pem"
      key: "{{ services_dir }}/traefik/certs/consul.key"
    - cert: "{{ services_dir }}/traefik/certs/grafana.pem"
      key: "{{ services_dir }}/traefik/certs/grafana.key"
    - cert: "{{ services_dir }}/traefik/certs/vault.pem"
      key: "{{ services_dir }}/traefik/certs/vault.key"

