---

# Grafana settings
grafana:
  dir: "{{ services_dir }}/grafana"
  dashboards_dir: "{{ services_dir }}/grafana/dashboards"

  host: "{{ private_network.address }}"
  port: 3000

  container:
    image: grafana/grafana:6.6.0
    name: grafana
    dns: "{{ private_network.address }}"
    network: ""
    restart: always

    syslog:
      enabled: yes
      host: unixgram:///dev/log
      tag: grafana

  dashboards: []

  datasources: {}
    # prometheus:
    #   name: Prometheus
    #   url: prometheus.service.consul

    # loki:
    #   name: Loki
    #   url: loki.service.consul

  frontend:
    domain: https://grafana.dev.clayman.pro

    auth:
      user: grafana
      password: grafana


# Vault settings
vault:
  service_dir: "{{ services_dir }}/vault"

  host: "{{ private_network.address }}"
  port: 8200

  container:
    image: vault:1.3.1
    name: vault
    restart: always
    network: ''

    syslog:
      enabled: true
      host: unixgram:///dev/log
      tag: vault


# Consul services settings
services:
  - name: grafana
    entries:
      - name: grafana
        host: "{{ grafana.host }}"
        port: "{{ grafana.port }}"
        tags:
          - "{{ env }}"
          - "traefik.enable=true"
          - "traefik.http.routers.grafana.rule=Host(`grafana.dev.clayman.pro`)"
          - "traefik.http.routers.grafana.entrypoints=web"
          - "traefik.http.routers.grafana.service=grafana"
          - "traefik.http.routers.grafana.middlewares=grafana-redirect@consulcatalog"
          - "traefik.http.routers.grafana-secure.rule=Host(`grafana.dev.clayman.pro`)"
          - "traefik.http.routers.grafana-secure.entrypoints=websecure"
          - "traefik.http.routers.grafana-secure.service=grafana"
          - "traefik.http.routers.grafana-secure.tls=true"
          - "traefik.http.middlewares.grafana-redirect.redirectscheme.scheme=https"
          - "traefik.http.middlewares.grafana-redirect.redirectscheme.permanent=true"
        meta:
          hostname: "{{ ansible_hostname }}"
          tier: "{{ env }}"

  - name: vault
    entries:
      - name: vault
        host: "{{ vault.host }}"
        port: "{{ vault.port }}"
        tags:
          - "{{ env }}"
          - "traefik.enable=true"
          - "traefik.http.routers.vault.rule=Host(`vault.dev.clayman.pro`)"
          - "traefik.http.routers.vault.entrypoints=web"
          - "traefik.http.routers.vault.service=vault"
          - "traefik.http.routers.vault.middlewares=vault-redirect@consulcatalog"
          - "traefik.http.routers.vault-secure.rule=Host(`vault.dev.clayman.pro`)"
          - "traefik.http.routers.vault-secure.entrypoints=websecure"
          - "traefik.http.routers.vault-secure.service=vault"
          - "traefik.http.routers.vault-secure.tls=true"
          - "traefik.http.middlewares.vault-redirect.redirectscheme.scheme=https"
          - "traefik.http.middlewares.vault-redirect.redirectscheme.permanent=true"
        meta:
          hostname: "{{ ansible_hostname }}"
          tier: "{{ env }}"
