---

- hosts: localhost

  tasks:
    - name: Prepare folders
      file: path="{{ item }}" state=directory
      with_items:
        - "{{ credentials_path }}/services/consul"
      tags:
        - consul

    - name: Generate consul encrypt
      shell: openssl rand -base64 32 > consul.encrypt
      args:
        chdir: "{{ credentials_path }}/services/consul"
        creates: consul.encrypt
      tags:
        - consul

- hosts: swarm
  become: true

  vars:
    swarm_tokens_path: "{{ credentials_path }}/services/swarm"

  tasks:
    - name: Create swarm
      import_role:
        name: docker
        tasks_from: swarm
      tags:
        - swarm


- hosts: servers
  become: true

  collections:
    - clayman083.cluster

  roles:
    - role: dnsmasq
    - role: consul

    - role: prometheus
    - role: loki
    - role: grafana
      when: grafana_enabled|default(False)

  tasks:
    - name: Add services to Consul Catalog
      import_role:
        name: consul
        tasks_from: services
      tags:
        - consul


- hosts: lb
  become: true

  collections:
    - clayman083.cluster

  roles:
    - role: traefik
      when: traefik_enabled|default(False)

  tasks:
    - name: Add services to Consul Catalog
      import_role:
        name: consul
        tasks_from: services
      vars:
        services:
          - name: traefik
            entries:
              - "{{ traefik_exporter_service }}"
      tags:
        - consul


- hosts: databases
  become: true

  roles:
    - role: postgresql
