---

- hosts: localhost

  tasks:
    - name: Prepare folders
      file: path="{{ item }}" state=directory
      with_items:
        - "{{ credentials_path }}/services/consul"
      tags:
        - consul

    - name: Generate consul encrypt
      shell: openssl rand -base64 32 > consul.encrypt
      args:
        chdir: "{{ credentials_path }}/services/consul"
        creates: consul.encrypt
      tags:
        - consul


# Configure local swarm cluster
- hosts: servers
  become: true

  vars:
    swarm_tokens_path: "{{ credentials_path }}/services/swarm"

  tasks:
    - name: Create swarm
      import_role:
        name: docker
        tasks_from: swarm
      tags:
        - swarm


# Configure service discovery
- hosts: servers
  become: true

  roles:
    - role: dnsmasq
    - role: consul

  tasks:
    - name: Add exporter to Consul Catalog
      import_role:
        name: consul
        tasks_from: services
      when: services|default(False)
      tags:
        - consul


# Configure monitoring
- hosts: servers
  become: true

  roles:
    - role: prometheus
    - role: loki
    - role: grafana


# Configure databases
- hosts: servers
  become: true

  roles:
    - postgresql


# Configure loadbalancers
- hosts: servers
  become: true

  roles:
    - role: traefik

  tasks:
    - name: Generate htpasswd for traefik
      htpasswd: path={{ item.path }} name={{ item.name }} password={{ item.password }}
      with_items:
        - path: "{{ traefik.conf_dir }}/consul.htpasswd"
          name: consul
          password: consul
        - path: "{{ traefik.conf_dir }}/prometheus.htpasswd"
          name: prometheus
          password: prometheus
        - path: "{{ traefik.conf_dir }}/alertmanager.htpasswd"
          name: alertmanager
          password: alertmanager
      tags:
        - traefik

    - name: Upload certificates
      import_role:
        name: traefik
        tasks_from: certificates
      vars:
        certificates: "{{ traefik_certificates }}"
      when: traefik_certificates|default([])
      tags:
        - traefik


# Configure services
- hosts: servers
  become: true

  roles:
    - role: passport
