---

public_network: "{{ ansible_eth0['ipv4'] }}"
private_network: "{{ ansible_eth1['ipv4'] }}"
docker_network: "{{ ansible_docker0['ipv4'] }}"

services_dir: /opt/services

# Syslog settings
syslog:
  master: yes
  nodes_logs_path: /var/log/nodes


# Registry settings
registry:
  domain: registry.clayman.pro

  image: registry:2
  container: registry
  network: backend


# Database settings
postgresql:
  version: 10

  max_connections: '25'
  superuser_reserved_connections: '3'

  shared_buffers: '256MB'
  work_mem: '32MB'
  maintenance_work_mem: '128MB'
  effective_cache_size: '128MB'

  log_min_duration_statement: '100'
  logging_collector: 'off'

  autovacuum: 'on'
  autovacuum_max_workers: 3

  users:
    backups:
      user: backups
      password: backups
    prometheus:
      user: "{{ postgresql_exporter.user }}"
      password: "{{ postgresql_exporter.password }}"
    passport:
      user: "{{ passport.database.user }}"
      password: "{{ passport.database.password }}"
    wallet:
      user: "{{ wallet.database.user }}"
      password: "{{ wallet.database.password }}"

  databases:
    passport:
      name: "{{ passport.database.name }}"
      owner: "{{ passport.database.user }}"
    wallet:
      name: "{{ wallet.database.name }}"
      owner: "{{ wallet.database.user }}"


postgresql_exporter:
  schema: prometheus

grafana:
  domain: grafana.clayman.pro

prometheus:
  domain: prometheus.clayman.pro

alertmanager:
  domain: alerts.clayman.pro


# Loadbalancer settings
loadbalancer:
  owner: dev@clayman.pro
  domains:
    consul:
      domains:
        - "{{ consul.domain }}"
    registry:
      domains:
        - "{{ registry.domain }}"
    
    alertmanager:
      domains:
        - "{{ alertmanager.domain }}"
    grafana: 
      domains: 
        - "{{ grafana.domain }}"
    prometheus:
      domains:
        - "{{ prometheus.domain }}"
    
    passport:
      domains:
        - "{{ passport.domain }}"
    wallet:
      domains:
        - "{{ wallet.domain }}"
