---

credentials_path: "./environments/.credentials"

env: local

public_network: "{{ ansible_en1['ipv4'][0] }}"
private_network: "{{ ansible_en1['ipv4'][0] }}"

services_dir: "{{ playbook_dir }}/playground"


superuser:
  name: "clayman"
  group: "clayman"


digitalocean:
  token: "{{ lookup('env','DO_TOKEN') }}"
  ssh_key: clayman-mac

  droplets: "{{ groups['droplets'] }}"

  image: 'debian-9-x64'
  region: 'ams3'
  size: '1gb'

  provision_user: 'root'


consul:
  domain: consul.dev.clayman.pro

  server: yes
  ui: yes


# Database settings
postgresql:
  users:
    prometheus:
      user: "{{ postgresql_exporter.user }}"
      password: "{{ postgresql_exporter.password }}"
    passport:
      user: "{{ passport.database.user }}"
      password: "{{ passport.database.password }}"
    wallet:
      user: "{{ wallet.database.user }}"
      password: "{{ wallet.database.password }}"

  databases:
    passport:
      name: "{{ passport.database.name }}"
      owner: "{{ passport.database.user }}"
    wallet:
      name: "{{ wallet.database.name }}"
      owner: "{{ wallet.database.user }}"


postgresql_exporter:
  schema: prometheus
  user: postgres
  password: postgres


# Passport settings
passport:
  secret_key: top_secret

  database:
    user: passport
    password: passport


# Wallet settings
wallet:
  database:
    user: wallet
    password: wallet