---

# Common settings
credentials_path: "{{ inventory_dir }}/.credentials"

services_dir: /opt/services

timezone: 'Asia/Yekaterinburg'


# Users settings
users:
  - name: clayman
    group: clayman
    sudoer: true
  - name: backups
    group: backups
