---

# Common settings
credentials_path: "{{ inventory_dir }}/.credentials"

services_dir: /opt/services

timezone: 'Asia/Yekaterinburg'

# Credentials settings
keys_dir: "{{ lookup('env','HOME') }}/.ssh/nodes/micro"
nodes: "{{ groups['servers'] }}"

# Users settings
users:
  - name: clayman
    group: clayman
    sudoer: true
  - name: backups
    group: backups
