---

# Common settings
private_network: "{{ ansible_eth1['ipv4'] }}"
public_network: "{{ ansible_eth0['ipv4'] }}"
docker_network: "{{ ansible_docker0['ipv4'] }}"


docker_exporter_service:
  name: docker-exporter
  host: "{{ private_network.address }}"
  port: 9323
  tags:
    - "{{ tier }}"
  meta:
    hostname: "{{ ansible_hostname }}"
    tier: "{{ tier }}"


# Swarm settings
swarm_node_labels:
  tier: "{{ tier }}"


# Consul settings
consul_host: "{{ private_network.address }}"
consul_image: consul:1.8.4

consul_agent_datacenter: dev
consul_agent_encrypt: "{{ lookup('hashivault', 'services/consul/server', 'encrypt', mount_point='/secrets', version=2) }}"
consul_agent_servers: "{{ groups['service_discovery'] }}"

consul_exporter_image: prom/consul-exporter:v0.7.1
consul_exporter_host: "{{ private_network.address }}"


# Prometheus settings
node_exporter_host: "{{ private_network.address }}"
node_exporter_image: prom/node-exporter:v1.0.1

cadvisor_host: "{{ private_network.address }}"
cadvisor_image: google/cadvisor:v0.33.0

blackbox_host: "{{ private_network.address }}"
blackbox_image: prom/blackbox-exporter:v0.17.0

prometheus_server_host: "{{ private_network.address }}"

# Minio settings
minio_image: minio/minio:RELEASE.2020-10-28T08-16-50Z
minio_host: "{{ private_network.address }}"

minio_access_key: "{{ lookup('hashivault', 'services/minio', 'access_key', mount_point='/secrets', version=2) }}"
minio_secret_key: "{{ lookup('hashivault', 'services/minio', 'secret_key', mount_point='/secrets', version=2) }}"


# Loki settings
loki_image: grafana/loki:1.6.1
loki_host: "{{ hostvars['alpha'].private_network.address }}"

promtail_image: grafana/promtail:1.6.1
promtail_host: "{{ private_network.address }}"
promtail_syslog_host: "{{ private_network.address }}"

promtail_syslog_labels:
  tier: "{{ tier }}"


# Grafana settings
grafana_image: grafana/grafana:7.2.1
grafana_host: "{{ private_network.address }}"


# Traefik settings
traefik_image: traefik:v2.3.2
traefik_entry_points:
  web:
    name: web
    host: "{{ public_network.address }}"
    internal_port: 80
    external_port: 80
  websecure:
    name: websecure
    host: "{{ public_network.address }}"
    internal_port: 443
    external_port: 443
  exporter:
    name: exporter
    host: "{{ private_network.address }}"
    internal_port: 8800
    external_port: 8800

traefik_access_log_enabled: false

traefik_container_dns_servers:
  - "{{ private_network.address }}"

traefik_file_provider_dir: /etc/traefik/conf.d
traefik_letsencrypt_resolver: acmeresolver
