---

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - binutils
      - curl
      - gcc
      - git
      - iptables
      - nano
      - mc
      - net-tools
      - tmux
      - vim
      - zsh
    state: latest
    update_cache: yes

- name: Configure timezone
  shell: echo "{{ timezone }}" > /etc/timezone
  when: "ansible_distribution == 'Debian'"
  notify: 'apply timezone'

- name: return motd to registered var
  command: "cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime"
  when: "ansible_distribution == 'Debian'"
  notify: 'apply timezone'

- include_tasks: swap.yml

- include_tasks: ssh.yml
  when: "ansible_distribution == 'Debian'"
