---

- name: Install dnsmasq
  homebrew:
    name: dnsmasq

- name: Create folders
  file: path=/usr/local/etc/dnsmasq.d state=directory

- name: Assemble config
  template: src=dnsmasq.conf.j2 dest=/usr/local/etc/dnsmasq.conf

- name: Assemble domains configs
  template: src=conf.d/{{ item }}.j2 dest=/usr/local/etc/dnsmasq.d/{{ item }}
  with_items:
    - consul.conf

- name: Restart service
  shell: brew services restart dnsmasq
  become: true