# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.box_check_update = false

  config.vm.define "dev" do |dev|
    dev.vm.box = "debian/stretch64"
    dev.vm.hostname = "dev"
    dev.vm.network "forwarded_port", guest: 80, host: 80
    dev.vm.network "forwarded_port", guest: 443, host: 443
    dev.vm.network "private_network", ip: "192.168.100.10"
    dev.disksize.size = "50GB"

    dev.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
    end
  end
end
