# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.box_check_update = false

  config.vm.define "alpha" do |alpha|
    alpha.vm.box = "debian/stretch64"
    alpha.vm.hostname = "alpha"
    alpha.vm.network "private_network", ip: "192.168.50.10"
#    alpha.disksize.size = "30GB"

    alpha.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define "bravo" do |bravo|
    bravo.vm.box = "debian/stretch64"
    bravo.vm.hostname = "bravo"
    bravo.vm.network "private_network", ip: "192.168.50.11"
#    bravo.disksize.size = "30GB"

    bravo.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
end
